name: Backend CI/CD

on:
  push:
    branches: [master]
    paths:
      - "server/**"
  pull_request:
    branches: [master]
    paths:
      - "server/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd server && npm install
